### ISSUE TITLE
Multipel Arguments Chrome Start not working

### ISSUE THREAD

**Issue by StanBarrows** [StanBarrows/raspberry-adscreens#21]
Multipel Arguments Chrome Start not working

- [ ]         chrome_options.add_argument("--kiosk")
- [ ]         #chrome_options.add_argument("--kiosk --noerrdialogs --disable-infobars")

**Comment by TrevisGordan** [comment]
Die Syntax zur add option ist:

```python
chrome_options.add_argument("--kiosk")
chrome_options.add_argument("--noerrdialogs")
chrome_options.add_argument("--disable-infobars")
```

@StanBarrows  Ich kann kurz eine Funktion schreiben und die aus der Config laden lassen?

**Comment by StanBarrows** [comment]
Ah ok einfach multiple adds geht für mich i.O.
